### ISSUE TITLE
route /api

### ISSUE THREAD

**Issue by hyww** [kevinwang309/InvoiceLedger#1]
/api的route也寫在loginRouter裡面好像有點怪怪的，我想把它拉出來，大家怎麼看XD

**Comment by kevinwang309** [comment]
其實那個file可以不用叫loginRouter 
可以改成router.js就好了
我是怕app.js裡面太雜

或是我loginRouter裡面那個 /api 改其他名字
然後把/api 放在外面

**Comment by CannedAnchovy** [comment]
現在才看到ＱＱ
